
// Authorization and Authentication using JWT is working prob
// saving our users
GET http://localhost:8080/posts
Authorization: 
###
POST http://localhost:4000/token
Content-type: application/json
{
    "token": ""
}

###
POST http://localhost:4000/login
Content-Type: application/json
    
{
    "username": ""
}